### ISSUE TITLE
To research about technologies such as: RDF, Virtuoso and SPARQL. To attach in this issue links regarding these technologies

### ISSUE THREAD

**Issue by evaldo** [evaldo/semanticdatabase#1]

**Comment by robsousantos** [comment]
[RDF e RDFS na Infra-estrutura de Suporte à Web Semântica.pdf](https://github.com/evaldo/semanticdatabase/files/894471/RDF.e.RDFS.na.Infra-estrutura.de.Suporte.a.Web.Semantica.pdf)
[Uma Visão da Web Semântica.pdf](https://github.com/evaldo/semanticdatabase/files/894472/Uma.Visao.da.Web.Semantica.pdf)
[Modelagem Semântica e Gerenciadores de Banco de Dados.PDF](https://github.com/evaldo/semanticdatabase/files/894473/Modelagem.Semantica.e.Gerenciadores.de.Banco.de.Dados.PDF)
[A GESTÃO DO CONHECIMENTO E DA INFORMAÇÃO CONCEITOS BÁSICOS.pdf](https://github.com/evaldo/semanticdatabase/files/894477/A.GESTAO.DO.CONHECIMENTO.E.DA.INFORMACAO.CONCEITOS.BASICOS.pdf)



seguem os linkis que venho utilizando como referencia 
____________________________________________________________________________

WEB SEMANTIC , O FUTURO DAS APLICAÇÕES JAVA ............ DEVMEDIA
http://www.devmedia.com.br/web-semantica-o-futuro-das-aplicacoes-java-magazine-85/18493

virtuoso DB
https://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VOSRDF

ENTENDA A IMPORTANCIA DO BANCO DE DADOS NA SUA EMPRESA
https://gmpe.com.br/blog/-entenda-a-importancia-do-banco-de-dados-da-sua-empresa-18.html

A INFORMAÇÃO O MAIOR PATRIMONIO DE UMA ORGANIZAÇÃO
http://www.artigos.com/artigos/1175-a-informacao-o-maior-patrimonio-de-uma-organizacao

A importancia de sistemas d einformação para empresas
http://www.administradores.com.br/artigos/marketing/a-importancia-do-sistema-de-informacao-gerencial-para-as-empresas/66425/

tipos de sistemas de informação nas organizações 
http://www.cbsi.net.br/2015/04/tipos-de-sistemas-de-informacao-nas-organizacoes.html

Estes já estou adicionando como referencia: 

Lassila, O.; Swick, R. (eds.). Resource Description Framework (RDF) model and syntaxspecification.1.0, 22 Feb 1999. (Recomendação do W3C). Disponível em:< https://www.w3.org/TR/1999/REC-rdf-syntax-19990222/>. Acesso em 04/ 04/ 2017.

Bray. Tim. Extensible Markup Language (XML) 1.0 (Fifth Edition) 26/11/2008 Recomendação W3C disponivel em < https://www.w3.org/TR/xml/ > acessado em 04 8 04 8 2017.
Cyganiak. Richard. RDF 1.1 Concepts and Abstract Syntax 25/ 02 / 2014 Recomendação W3C disponivel em < https://www.w3.org/TR/rdf11-concepts/ > acessado em 04 / 04 / 2017.

Gandon. Fabien. Sintaxe XML RDF 1.1 02 / 2014. Recomendação do W3C). Disponível em: < https://www.w3.org/TR/rdf-syntax-grammar/ > acessado em 04/ 04 / 2017. 
 
Sobre o W3C. Disponivel em < https://www.w3.org/Consortium/> acessado em  04/ 04/ 2017

**Comment by evaldo** [comment]
Issue has been finished.
