### ISSUE TITLE
Execute accessing in GitHub repository

### ISSUE THREAD

**Issue by evaldo** [evaldo/semanticdatabase#2]
Using this GitHub repository: https://github.com/evaldo/semanticdatabase.git

**Comment by evaldo** [comment]
Robson, peço que atualize neste repositório para eu dar prosseguimento no projeto.

**Comment by robsousantos** [comment]
Bom dia, Já estou utilizando este repositório ainda não iniciei o projeto do banco de dados. Por favor me informe a ferramena que esta sendo utilizada pelos demais ( eclipse ou netbeans ) para que eu possa criar um projeto.

**Comment by robsousantos** [comment]
Boa tarde Evaldo, estou passando apenas para atualiza lo sobre os estudos. Devido a uma certa dificuldade de instalar o virtuoso no windows ( mesmo seguinto os passos recomendados no site do mesmo ) criei uma maquina virtual com Linux (ubunto ) em meu notebook e já tenho o Virtuoso instalado na mesma, a partir deste momento iniciarei os estudos sobre os comandos basicos de manipulação de arquivos RDF na base de dados.
